import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { useRouter } from 'expo-router';
import { Screen, H1, H2, Body, Muted, Button, Card } from '../components/ui';
import { StatusLegend } from '../components/StatusLegend';
import { setOnboarded } from '../lib/auth';
import { useBrand, useTheme, makeStyles } from '../brand';

interface Slide {
  title: string;
  body: React.ReactNode;
}

const TASK_TYPES: { icon: string; name: string; desc: string }[] = [
  { icon: '🔋', name: 'Battery swap', desc: 'Low battery. Record voltage before/after; vehicle returns to service automatically.' },
  { icon: '↔️', name: 'Rebalance', desc: 'Move idle vehicles from low-demand to high-demand zones. Watch the zone target counts.' },
  { icon: '🔧', name: 'Repair', desc: 'Fix a fault. Photo the issue before and the result after.' },
  { icon: '🔍', name: 'Inspect', desc: 'Safety check: brakes, lights, throttle. Auto-created when a vehicle is offline > 24h or after a fall alarm.' },
  { icon: '📦', name: 'Pickup', desc: 'Collect a vehicle onto the van for the workshop.' },
  { icon: '📍', name: 'Deploy', desc: 'Place a vehicle in the field and set it available. Use Deploy mode for batches.' },
];

export default function Onboarding() {
  const router = useRouter();
  const theme = useTheme();
  const st = useStyles(theme);
  const { c, space } = theme;
  const { brand, opsName } = useBrand();
  const [i, setI] = useState(0);

  const slides: Slide[] = [
    {
      title: `Welcome to ${opsName}`,
      body: (
        <View style={{ gap: space.md }}>
          <Body>Your field service tool for the {brand.name} fleet. Big buttons, high contrast, built for outdoor use with gloves.</Body>
          <Card>
            <H2>Status colors</H2>
            <Muted>You&apos;ll see every vehicle on the map — not just available ones.</Muted>
            <View style={{ marginTop: space.sm }}>
              <StatusLegend />
            </View>
          </Card>
        </View>
      ),
    },
    {
      title: 'Task types',
      body: (
        <View style={{ gap: space.sm }}>
          <Muted>Tasks come from admins or are auto-generated by system rules (shown with an “Auto” tag).</Muted>
          {TASK_TYPES.map((t) => (
            <Card key={t.name} style={{ flexDirection: 'row', gap: space.md, alignItems: 'center' }}>
              <Text style={{ fontSize: 28 }}>{t.icon}</Text>
              <View style={{ flex: 1 }}>
                <Text style={st.tt}>{t.name}</Text>
                <Muted>{t.desc}</Muted>
              </View>
            </Card>
          ))}
        </View>
      ),
    },
    {
      title: 'Works fully offline',
      body: (
        <View style={{ gap: space.md }}>
          <Card style={{ borderColor: c.primary }}>
            <H2>📴 Offline-first</H2>
            <Body>Everything works with no signal. The app reads from an on-device database and saves every action to a local queue.</Body>
          </Card>
          <Card>
            <H2>🔁 Auto-sync</H2>
            <Body>When you&apos;re back online, queued actions upload automatically — deduplicated so nothing double-applies. The pill at the top shows “N pending • syncing…”.</Body>
          </Card>
          <Card>
            <H2>📷 Photos everywhere</H2>
            <Body>Task steps, damage reports, status changes and deploys attach photos. Offline photos queue and upload later.</Body>
          </Card>
          <Card>
            <H2>⚖️ Conflict rule</H2>
            <Muted>Server wins on vehicle status; your completed tasks are never lost.</Muted>
          </Card>
        </View>
      ),
    },
  ];

  const last = i === slides.length - 1;
  const slide = slides[i]!;

  async function finish() {
    await setOnboarded();
    router.replace('/(tabs)');
  }

  return (
    <Screen>
      <View style={{ flex: 1, gap: space.lg }}>
        <View style={st.dots}>
          {slides.map((_, k) => (
            <View key={k} style={[st.dot, k === i && st.dotActive]} />
          ))}
        </View>
        <H1>{slide.title}</H1>
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ paddingBottom: space.xl }}>
          {slide.body}
        </ScrollView>
        <View style={{ gap: space.sm }}>
          <Button title={last ? 'Start working' : 'Next'} onPress={last ? finish : () => setI(i + 1)} />
          {!last && <Button title="Skip" variant="ghost" onPress={finish} />}
        </View>
      </View>
    </Screen>
  );
}

const useStyles = makeStyles((t) => ({
  dots: { flexDirection: 'row', gap: 6, justifyContent: 'center' },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: t.c.border },
  dotActive: { backgroundColor: t.c.primary, width: 24 },
  tt: { color: t.c.text, fontWeight: '700', fontSize: t.font.size.md },
}));
